### ISSUE TITLE
Proto2gql: Implement bytes scalartype

### ISSUE THREAD

**Issue by gponsinet** [EGT-Ukraine/go2gql#2]
Hello,

When I tried to gen go code I had the following error.

```
panic: failed to prepare generator: failed to prepare plugin proto2gql:
  failed to prepare file for generation: failed to prepare file input objects:
  failed to resolve field type: failed to get input type resolver: unimplemented scalar type: bytes  goroutine 1 [running]:
  main.main.func1(0xc4200c8000, 0xc4200c8000, 0x4)
  /Users/godefroy/.go/src/github.com/EGT-Ukraine/go2gql/cmd/go2gql/main.go:55 +0x35b
  github.com/urfave/cli.(*App).Run(0xc4203f4000, 0xc4200a8090, 0x3, 0x3, 0x0, 0x0)
  /Users/godefroy/.go/src/github.com/urfave/cli/app.go:244 +0x738 main.main()
  /Users/godefroy/.go/src/github.com/EGT-Ukraine/go2gql/cmd/go2gql/main.go:100 +0x38d
```

Then I tried to fix it in https://github.com/EGT-Ukraine/go2gql/pull/1
Can you please review it and say me if I did it well.

**Comment by saturn4er** [comment]
Hi, @gponsinet.
Just fixed this issue in PR #22.
